# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ab0926ce0d5086e66c73e55a874bad141e0949872e079999f1eaf6d714165925b12e37dff2c94a2b9fca10313142df9a6763e1b16121cdcd3344e6118d9223

test:
  secret_key_base: 5b957986a52a6cbae55104f3aa956b3d186cde992f15149b8041e9409e314242e870917f3b1998ed0d30c4bd028f97388e7d8a85aca7fef3e4b5c57400331f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
